/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Persistencia.Persistencia;
import Sistema.Sistema;
import java.io.IOException;

/**
 *
 * @author javierfernandez
 */
public class PanelPrincipal extends javax.swing.JFrame {
    private Sistema sistema;
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelPrincipal.class.getName());

    /**
     * Creates new form panelPrincipal
     */
    public PanelPrincipal(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBackground = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAreas = new javax.swing.JMenu();
        MenuAreaAlta = new javax.swing.JMenuItem();
        MenuAreaBaja = new javax.swing.JMenuItem();
        MenuAreaModificacion = new javax.swing.JMenuItem();
        MenuAreaRealizarMovimiento = new javax.swing.JMenuItem();
        menuManagers = new javax.swing.JMenu();
        MenuManagerAlta = new javax.swing.JMenuItem();
        MenuManagerBaja = new javax.swing.JMenuItem();
        MenuManagerModificacion = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        MenuEmpleadoAlta = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        MenuReporteInteligente = new javax.swing.JMenuItem();
        MenuReporteDeAreas = new javax.swing.JMenuItem();
        MenuReporteDeMovimientos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERP Empresarial");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/img/fondoAppChico.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbBackground)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 347, Short.MAX_VALUE)
        );

        menuAreas.setText("Áreas");

        MenuAreaAlta.setText("Alta");
        MenuAreaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAreaAltaActionPerformed(evt);
            }
        });
        menuAreas.add(MenuAreaAlta);

        MenuAreaBaja.setText("Baja");
        MenuAreaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAreaBajaActionPerformed(evt);
            }
        });
        menuAreas.add(MenuAreaBaja);

        MenuAreaModificacion.setText("Modificación");
        MenuAreaModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAreaModificacionActionPerformed(evt);
            }
        });
        menuAreas.add(MenuAreaModificacion);

        MenuAreaRealizarMovimiento.setText("Realizar movimiento");
        MenuAreaRealizarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAreaRealizarMovimientoActionPerformed(evt);
            }
        });
        menuAreas.add(MenuAreaRealizarMovimiento);

        menuPrincipal.add(menuAreas);

        menuManagers.setText("Managers");

        MenuManagerAlta.setText("Alta");
        MenuManagerAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManagerAltaActionPerformed(evt);
            }
        });
        menuManagers.add(MenuManagerAlta);

        MenuManagerBaja.setText("Baja");
        MenuManagerBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManagerBajaActionPerformed(evt);
            }
        });
        menuManagers.add(MenuManagerBaja);

        MenuManagerModificacion.setText("Modificación");
        MenuManagerModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManagerModificacionActionPerformed(evt);
            }
        });
        menuManagers.add(MenuManagerModificacion);

        menuPrincipal.add(menuManagers);

        menuEmpleados.setText("Empleados");

        MenuEmpleadoAlta.setText("Alta");
        MenuEmpleadoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmpleadoAltaActionPerformed(evt);
            }
        });
        menuEmpleados.add(MenuEmpleadoAlta);

        menuPrincipal.add(menuEmpleados);

        menuReportes.setText("Reportes");

        MenuReporteInteligente.setText("Reporte inteligente");
        MenuReporteInteligente.setToolTipText("");
        menuReportes.add(MenuReporteInteligente);

        MenuReporteDeAreas.setText("Reporte de estado de áreas");
        MenuReporteDeAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReporteDeAreasActionPerformed(evt);
            }
        });
        menuReportes.add(MenuReporteDeAreas);

        MenuReporteDeMovimientos.setText("Reporte de movimientos");
        MenuReporteDeMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReporteDeMovimientosActionPerformed(evt);
            }
        });
        menuReportes.add(MenuReporteDeMovimientos);

        menuPrincipal.add(menuReportes);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAreaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAreaAltaActionPerformed

    java.awt.EventQueue.invokeLater(() -> new VentanaAltaArea(sistema).setVisible(true));
     
    
    

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAreaAltaActionPerformed

    private void MenuAreaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAreaBajaActionPerformed
           java.awt.EventQueue.invokeLater(() -> new VentanaBajaArea(sistema).setVisible(true));

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAreaBajaActionPerformed

    private void MenuAreaModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAreaModificacionActionPerformed
    
        java.awt.EventQueue.invokeLater(() -> new VentanaModificacionArea(sistema).setVisible(true));


    // TODO add your handling code here:
    }//GEN-LAST:event_MenuAreaModificacionActionPerformed

    private void MenuManagerAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManagerAltaActionPerformed
    
        java.awt.EventQueue.invokeLater(() -> new VentanaAltaManager(sistema).setVisible(true));

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuManagerAltaActionPerformed

    private void MenuManagerBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManagerBajaActionPerformed
        
        java.awt.EventQueue.invokeLater(() -> new VentanaBajaManager(sistema).setVisible(true));

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuManagerBajaActionPerformed

    private void MenuManagerModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManagerModificacionActionPerformed
    java.awt.EventQueue.invokeLater(() -> new VentanaModificacionManager(sistema).setVisible(true));

        
    // TODO add your handling code here:
    }//GEN-LAST:event_MenuManagerModificacionActionPerformed

    private void MenuEmpleadoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmpleadoAltaActionPerformed
        java.awt.EventQueue.invokeLater(() -> new VentanaAltaEmpleado(sistema).setVisible(true));

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuEmpleadoAltaActionPerformed

    private void MenuAreaRealizarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAreaRealizarMovimientoActionPerformed
        java.awt.EventQueue.invokeLater(() -> new VentanaMovimientoArea(sistema).setVisible(true));

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAreaRealizarMovimientoActionPerformed

    private void MenuReporteDeAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReporteDeAreasActionPerformed

        java.awt.EventQueue.invokeLater(() -> new VentanaReporteEstadoArea(sistema).setVisible(true));


        // TODO add your handling code here:
    }//GEN-LAST:event_MenuReporteDeAreasActionPerformed

    private void MenuReporteDeMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReporteDeMovimientosActionPerformed

        java.awt.EventQueue.invokeLater(() -> new VentanaReporteMovimientos(sistema).setVisible(true));


        // TODO add your handling code here:
    }//GEN-LAST:event_MenuReporteDeMovimientosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        try {
            //Guardar los datos
            
            Persistencia.guardarSistema(sistema);
        
            
        } catch (IOException ex) {
            System.getLogger(PanelPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
            }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAreaAlta;
    private javax.swing.JMenuItem MenuAreaBaja;
    private javax.swing.JMenuItem MenuAreaModificacion;
    private javax.swing.JMenuItem MenuAreaRealizarMovimiento;
    private javax.swing.JMenuItem MenuEmpleadoAlta;
    private javax.swing.JMenuItem MenuManagerAlta;
    private javax.swing.JMenuItem MenuManagerBaja;
    private javax.swing.JMenuItem MenuManagerModificacion;
    private javax.swing.JMenuItem MenuReporteDeAreas;
    private javax.swing.JMenuItem MenuReporteDeMovimientos;
    private javax.swing.JMenuItem MenuReporteInteligente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JMenu menuAreas;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenu menuManagers;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
