/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Dominio.Personas.Manager;
import Sistema.Sistema;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;

/**
 *
 * @author javierfernandez
 */
public class VentanaModificacionManager extends javax.swing.JFrame implements Observer {
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaModificacionManager.class.getName());

    /**
     * Creates new form VentanaModificacionManager
     */
    public VentanaModificacionManager(Sistema sistema) {
        this.sistema = sistema;
        this.sistema.addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaManager = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputModificarCelularManager = new javax.swing.JTextField();
        btnModificarManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cédula", "Años de antigüedad", "Celular", "Empleados a Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaManager);

        jLabel1.setText("Nuevo teléfono:");

        btnModificarManager.setText("Cambiar Télefono");
        btnModificarManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(btnModificarManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputModificarCelularManager))
                        .addGap(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)))
                        .addComponent(inputModificarCelularManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarManager)
                        .addGap(74, 74, 74)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.actualizarManagers();

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnModificarManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarManagerActionPerformed
        
        int filaSeleccionada = tablaManager.getSelectedRow();
        
        String nuevoTelefono = inputModificarCelularManager.getText();
        
        if (filaSeleccionada >= 0 && nuevoTelefono.matches("\\d+")) { 
        
            String nombre = (String) tablaManager.getValueAt(filaSeleccionada, 0);
            int cedula = (Integer) tablaManager.getValueAt(filaSeleccionada, 1);
            String celular = (String) tablaManager.getValueAt(filaSeleccionada, 3);
            int antiguedad = (Integer) tablaManager.getValueAt(filaSeleccionada, 2);
            

            Manager managerSeleccionado = new Manager(nombre,cedula,celular,antiguedad);

            for(int i = 0; i < this.sistema.getListaPersonas().getManagersOrdenados().size(); i++){

                Manager manager = this.sistema.getListaPersonas().getManagersOrdenados().get(i);

                if(managerSeleccionado.equals(manager)){

                    manager.setCelular(nuevoTelefono);

                }

            }

            inputModificarCelularManager.setText("");

        }else if(filaSeleccionada >= 0){
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione un manager de la tabla", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }else if(!nuevoTelefono.matches("\\d+")){
        javax.swing.JOptionPane.showMessageDialog(this, "Solo es posible ingresar números.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarManagerActionPerformed

    
    public void actualizarManagers() {
    javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaManager.getModel();
    modeloTabla.setRowCount(0); 
    
    for (int i = 0; i < this.sistema.getManagersOrdenados().size(); i++) {
        Manager manager = this.sistema.getManagersOrdenados().get(i);
        int cantidadDeEmpleados = this.sistema.cantidadDeEmpleadosDeUnManager(manager);
        
        modeloTabla.addRow(new Object[]{
            manager.getNombre(),
            manager.getCedula(),
            manager.getAnosDeAntiguedad(),
            manager.getCelular(),
            cantidadDeEmpleados
                
            });
        }
    }
    
    //PREGUNTAR EN CLASE!!!
    @Override
    public void update(Observable o, Object arg) {
        if (o == sistema) {
            // Actualiza la interfaz gráfica en el hilo de eventos de Swing
            SwingUtilities.invokeLater(() -> {
                actualizarManagers();  // Método que actualiza el JList
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarManager;
    private javax.swing.JTextField inputModificarCelularManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaManager;
    // End of variables declaration//GEN-END:variables
}
