/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import DatosPrecargados.DatosPrecargados;
import Sistema.Sistema;

/**
 *
 * @author javierfernandez
 */
public class VentanaInicio extends javax.swing.JFrame {
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form ventanaInicio
     */
    public VentanaInicio(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSistemaConDatosPrecargados = new javax.swing.JButton();
        btnSistemaGuardado = new javax.swing.JButton();
        btnSistemaNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comenzar con...");

        btnSistemaConDatosPrecargados.setText("Sistema con datos precargados");
        btnSistemaConDatosPrecargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaConDatosPrecargadosActionPerformed(evt);
            }
        });

        btnSistemaGuardado.setText("Sistema guardado");
        btnSistemaGuardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaGuardadoActionPerformed(evt);
            }
        });

        btnSistemaNuevo.setText("Sistema Nuevo");
        btnSistemaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSistemaNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnSistemaGuardado)
                .addGap(18, 18, 18)
                .addComponent(btnSistemaConDatosPrecargados)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSistemaGuardado)
                    .addComponent(btnSistemaNuevo)
                    .addComponent(btnSistemaConDatosPrecargados))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSistemaGuardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaGuardadoActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaGuardadoActionPerformed

    private void btnSistemaConDatosPrecargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaConDatosPrecargadosActionPerformed
    
    java.awt.EventQueue.invokeLater(() -> new PanelPrincipal(this.sistema).setVisible(true));
    this.setVisible(false);
    
    new DatosPrecargados(this.sistema);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaConDatosPrecargadosActionPerformed

    private void btnSistemaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaNuevoActionPerformed
    
      
    java.awt.EventQueue.invokeLater(() -> new PanelPrincipal(this.sistema).setVisible(true));
    this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaNuevoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSistemaConDatosPrecargados;
    private javax.swing.JButton btnSistemaGuardado;
    private javax.swing.JButton btnSistemaNuevo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
