/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Historial.CambioArea;
import Historial.ListaCambioArea;
import Sistema.Sistema;
import Dominio.Personas.Empleado;
import Dominio.Areas.Area;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Camila
 */
public class VentanaReporteMovimientos extends javax.swing.JFrame implements Observer {
    
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReporteMovimientos.class.getName());
    private final Sistema sistema;
    
    
    //Llama a cargas filtros y cargar tabla movimientos para cargar todos los movimientos existenes 
     public VentanaReporteMovimientos(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        this.sistema.addObserver(this);
        cargarFiltros();
        cargarTablaMovimientos(sistema.getListaCambioArea().getListaCambios());
    }
//trae los datos de areas y empleados para el select que corresponde 
    private void cargarFiltros() {
        // Empleados
        selectEmpleado.removeAllItems();
        selectEmpleado.addItem("Todos");
        for (Empleado emp : sistema.getListaPersonas().getEmpleadosOrdenados()) {
            selectEmpleado.addItem(emp.getNombre());
        }
        // Áreas
        selectArea.removeAllItems();
        selectArea.addItem("Todas");
        for (Area area : sistema.getListaAreas().getAreas()) {
            selectArea.addItem(area.getNombre());
        }
    }
//revisar
    private void cargarTablaMovimientos(ArrayList<CambioArea> movimientos) {
        DefaultTableModel model = (DefaultTableModel) tablaMovimientos.getModel();
    model.setRowCount(0); //elimina las filas de la tabla
    movimientos.sort((m1, m2) -> Integer.compare(m1.getMesInicio(), m2.getMesInicio()));//Ordena la lista segun el mes,
    for (CambioArea mov : movimientos) { //recorre la lista de objetos CambioArea en la lista de movimientos
        // Mostrar solo movimientos con área de origen, si no tiene area de origen pasa al siguiente movimiento
        if (mov.getNombreAreaAnterior() == null || mov.getNombreAreaAnterior().isEmpty()) {
            continue; // Ignorar las altas
        }
        String mes = nombreMes(mov.getMesInicio()); //obtiene el numero del mes del cambio y lo cambia a nombre
       
        String areaOrig = mov.getNombreAreaAnterior(); //guarda area de origen
        String areaDest = mov.getNombreAreaNueva(); //guarda area destino
        String empleado = mov.getEmpleado().getNombre();//guarda nombre empleado
        model.addRow(new Object[]{mes, areaOrig, areaDest, empleado}); //le paso un arreglo de objetos para que genere la fila
    }
    }

    private String nombreMes(int mesNum) {
        String[] nombres = { "", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
            "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" };
        return (mesNum >= 1 && mesNum <= 12) ? nombres[mesNum] : "";
    }

    private ArrayList<CambioArea> filtrarMovimientos() {
        // Obtiene el valor seleccionado en cada JComboBox de filtro (mes, área y empleado)
        String selMes = (String) selectMes.getSelectedItem();
        String selArea = (String) selectArea.getSelectedItem();
        String selEmpleado = (String) selectEmpleado.getSelectedItem();

        ArrayList<CambioArea> todos = sistema.getListaCambioArea().getListaCambios();
        ArrayList<CambioArea> filtrados = new ArrayList<>();
        //Recorre la lista de movimientos, dependiendo del filtro es lo que muestra
        for (CambioArea mov : todos) {
            boolean filtrarMes = selMes.equals("Todos") || nombreMes(mov.getMesInicio()).equals(selMes);
            boolean filtrarArea = selArea.equals("Todas") ||
                (mov.getNombreAreaAnterior() != null && mov.getNombreAreaAnterior().equals(selArea)) ||
                (mov.getNombreAreaNueva() != null && mov.getNombreAreaNueva().equals(selArea));
            boolean filtrarEmpleado = selEmpleado.equals("Todos") ||
                mov.getEmpleado().getNombre().equals(selEmpleado);
            if (filtrarMes && filtrarArea && filtrarEmpleado) {
                filtrados.add(mov);
            }
        }
        return filtrados;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        selectArea = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        selectEmpleado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMovimientos = new javax.swing.JTable();
        btnfiltrar = new javax.swing.JButton();
        btnborrarfiltro = new javax.swing.JButton();
        exportarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setForeground(new java.awt.Color(255, 102, 0));

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Mes:");

        selectMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        selectMes.setToolTipText("");
        selectMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMesActionPerformed(evt);
            }
        });

        jLabel2.setText("Área:");

        selectArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas" }));

        jLabel3.setText("Empleado/a:");

        selectEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        selectEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEmpleadoActionPerformed(evt);
            }
        });

        tablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mes", "Área Origen", "Área Destino", "Empleado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMovimientos);

        btnfiltrar.setText("FILTRAR");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });

        btnborrarfiltro.setText("BORRAR FILTRO");
        btnborrarfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarfiltroActionPerformed(evt);
            }
        });

        exportarReporte.setText("EXPORTAR REPORTE");
        exportarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exportarReporte)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectMes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnfiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnborrarfiltro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exportarReporte)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(selectArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(selectEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnfiltrar)
                        .addComponent(btnborrarfiltro))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectMesActionPerformed

    private void selectEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectEmpleadoActionPerformed

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
      cargarTablaMovimientos(filtrarMovimientos());  // TODO add your handling code here:
    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void btnborrarfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarfiltroActionPerformed
         selectMes.setSelectedIndex(0); //Cuando selecciono borrar filtro, vuelve a la posicion 0, que es "todos" en cada select
        selectArea.setSelectedIndex(0);
        selectEmpleado.setSelectedIndex(0);
        cargarTablaMovimientos(sistema.getListaCambioArea().getListaCambios());// TODO add your handling code here:
    }//GEN-LAST:event_btnborrarfiltroActionPerformed

    private void exportarReporteActionPerformed(java.awt.event.ActionEvent evt) {   
        //Intentar hacerlo con hasNextLine y nextLine()
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Guardar reporte de movimientos");
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String filename = file.getAbsolutePath();
        if (!filename.toLowerCase().endsWith(".csv")) {
            filename += ".csv";
            file = new File(filename);
        }
            try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
                pw.println("Mes,Área Origen,Área Destino,Empleado");
                DefaultTableModel model = (DefaultTableModel) tablaMovimientos.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    String mes = model.getValueAt(i, 0).toString();
                    String areaO = model.getValueAt(i, 1).toString();
                    String areaD = model.getValueAt(i, 2).toString();
                    String emp = model.getValueAt(i, 3).toString();
                    pw.println(mes + "," + areaO + "," + areaD + "," + emp);
                }
                pw.flush();
                JOptionPane.showMessageDialog(this, "Reporte exportado correctamente");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al exportar");
            }
        }
    }   
    @Override
    public void update(Observable o, Object arg) {
        if (o == sistema) {
            
             cargarFiltros();
            
        }
    }
   

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrarfiltro;
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JButton exportarReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectArea;
    private javax.swing.JComboBox<String> selectEmpleado;
    private javax.swing.JComboBox<String> selectMes;
    private javax.swing.JTable tablaMovimientos;
    // End of variables declaration//GEN-END:variables
}
