/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Dominio.Areas.Area;
import Dominio.Personas.Empleado;
import Sistema.Sistema;
import IA.ServicioGemini;
import FuncionalidadTexto.ArchivoLectura;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.SwingWorker;
import javax.swing.JOptionPane;

/**
 *
 * @author javierfernandez
 */
public class VentanaReporteInteligente extends javax.swing.JFrame {
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReporteInteligente.class.getName());

    /**
     * Creates new form VentanaReporteInteligente
     */
    public VentanaReporteInteligente(Sistema sistema) {
        this.sistema = sistema;

        initComponents();
        actualizarAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerarReporte = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaNuevaArea = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaArea = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula", "Salario Mensual", "Área"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaEmpleados);

        tablaNuevaArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaNuevaArea);

        tablaArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAreaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaArea);

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout btnGenerarReporteLayout = new javax.swing.GroupLayout(btnGenerarReporte);
        btnGenerarReporte.setLayout(btnGenerarReporteLayout);
        btnGenerarReporteLayout.setHorizontalGroup(
            btnGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReporteLayout.createSequentialGroup()
                .addGroup(btnGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnGenerarReporteLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(btnGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(btnGenerarReporteLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(btnGenerarReporteLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(jButton1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        btnGenerarReporteLayout.setVerticalGroup(
            btnGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReporteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(btnGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAreaMouseClicked
       
        
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaArea.getModel();
        int filaSeleccionada = tablaArea.getSelectedRow();
        String nombreAreaSeleccionada = (String) tablaArea.getValueAt(filaSeleccionada, 0);
        actualizarEmpleados(this.sistema.getAreaPorNOmbre(nombreAreaSeleccionada));
        
        areasSinLaSeleccionada();
        
        
    }//GEN-LAST:event_tablaAreaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generarReporteInteligente();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    public void actualizarEmpleados(Area areaSelecionada) {
    javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaEmpleados.getModel();
    modeloTabla.setRowCount(0); 
    
    for (int i = 0; i < areaSelecionada.getListaEmpleados().size(); i++) {
        
        Empleado empleado = areaSelecionada.getListaEmpleados().get(i);
        
        
        
        modeloTabla.addRow(new Object[]{
            empleado.getNombre(),
            empleado.getCedula(),
            empleado.getSalarioMensual(),
            this.sistema.getAreaDelEmpleado(empleado).getNombre(),
            
            });
        
        }

    }
    
    private void actualizarAreas(){
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaArea.getModel();
        modeloTabla.setRowCount(0); 
        
        
        
        for(int i = 0; i < this.sistema.getAreasOrdenadasPorNombre().size(); i++){
          
            Area area = this.sistema.getAreasOrdenadasPorNombre().get(i);

            modeloTabla.addRow(new Object[]{
                    area.getNombre(),
                    

            });
            
            

        }
    }
    
    public void areasSinLaSeleccionada(){
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaNuevaArea.getModel();
        modeloTabla.setRowCount(0); 
        int filaSeleccionadaTablaAreaOriginal = tablaArea.getSelectedRow();

        for(int i = 0; i < this.sistema.getAreasOrdenadasPorNombre().size(); i++){
        if(i != filaSeleccionadaTablaAreaOriginal){
            Area area = this.sistema.getAreasOrdenadasPorNombre().get(i);

                modeloTabla.addRow(new Object[]{
                    area.getNombre()
                    

                    });

                }
        }
        
    }
    
    private void generarReporteInteligente() {
        // Validar selecciones
        int filaEmpleadoSeleccionada = tablaEmpleados.getSelectedRow();
        int filaAreaDestinoSeleccionada = tablaNuevaArea.getSelectedRow();
        int filaAreaOrigenSeleccionada = tablaArea.getSelectedRow();
        
        if (filaEmpleadoSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (filaAreaDestinoSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un área de destino", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (filaAreaOrigenSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un área de origen", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Obtener datos seleccionados
        int cedulaEmpleado = (Integer) tablaEmpleados.getValueAt(filaEmpleadoSeleccionada, 1);
        Empleado empleadoSeleccionado = sistema.getListaPersonas().getEmpleadoPorCedula(cedulaEmpleado);
        
        String nombreAreaOrigen = (String) tablaArea.getValueAt(filaAreaOrigenSeleccionada, 0);
        Area areaOrigen = sistema.getAreaPorNOmbre(nombreAreaOrigen);
        
        String nombreAreaDestino = (String) tablaNuevaArea.getValueAt(filaAreaDestinoSeleccionada, 0);
        Area areaDestino = sistema.getAreaPorNOmbre(nombreAreaDestino);
        
        // Leer CV del empleado
        String cvEmpleado = leerCV(empleadoSeleccionado.getCedula());
        
        // Mostrar indicador de carga
        jTextArea1.setText("Generando reporte inteligente...\nPor favor espere, consultando a la IA...");
        jButton1.setEnabled(false);
        
        // Ejecutar consulta a la API en un hilo separado
        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                try {
                    ServicioGemini servicioGemini = new ServicioGemini();
                    return servicioGemini.generarReporteInteligente(
                        areaOrigen.getNombre(),
                        areaOrigen.getDescripcion(),
                        areaDestino.getNombre(),
                        cvEmpleado
                    );
                } catch (Exception e) {
                    throw e;
                }
            }
            
            @Override
            protected void done() {
                try {
                    String reporte = get();
                    jTextArea1.setText(reporte);
                } catch (Exception e) {
                    String errorMsg = "Error al generar el reporte: " + e.getMessage();
                    errorMsg += "\n\nVerifique que:\n" +
                               "1. La variable de entorno ERP_API_KEY esté configurada\n" +
                               "2. Tenga conexión a internet\n" +
                               "3. La API key de Gemini sea válida\n" +
                               "4. La librería google-genai esté en el classpath";
                    jTextArea1.setText(errorMsg);
                } finally {
                    jButton1.setEnabled(true);
                }
            }
        };
        
        worker.execute();
    }
    
    private String leerCV(int cedulaEmpleado) {
        try {
            String rutaArchivo = "cvs/CV" + cedulaEmpleado;
            Path archivoCv = Paths.get(rutaArchivo);
            
            if (Files.exists(archivoCv)) {
                ArchivoLectura archivoLectura = new ArchivoLectura(rutaArchivo);
                StringBuilder contenidoCV = new StringBuilder();
                
                while (archivoLectura.hayMasLineas()) {
                    contenidoCV.append(archivoLectura.linea()).append("\n");
                }
                
                archivoLectura.cerrar();
                return contenidoCV.toString();
            } else {
                return "CV no disponible para el empleado con cédula: " + cedulaEmpleado + 
                       "\nSe utilizará información básica del empleado.";
            }
        } catch (Exception e) {
            return "Error al leer el CV: " + e.getMessage() + 
                   "\nSe utilizará información básica del empleado.";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnGenerarReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tablaArea;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaNuevaArea;
    // End of variables declaration//GEN-END:variables
}
