/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import Dominio.Areas.Area;
import Sistema.Sistema;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;


/**
 *
 * @author javierfernandez
 */
public class VentanaAltaArea extends javax.swing.JFrame implements Observer{
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAltaArea.class.getName());
    
    /**
     * Creates new form VentanaAreaAlta
     */
    public VentanaAltaArea(Sistema sistema) {
        this.sistema = sistema;
        this.sistema.addObserver(this);
        
        initComponents();
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNombreArea = new javax.swing.JLabel();
        lbPresupuestoArea = new javax.swing.JLabel();
        lbDescripcionArea = new javax.swing.JLabel();
        areaAltaInputNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaAltaInputDescipcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAreas = new javax.swing.JList<>();
        btnAgregarArea = new javax.swing.JButton();
        areaAltaInputPresupuesto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Área");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbNombreArea.setText("Nombre");

        lbPresupuestoArea.setText("Presupuesto (USD)");

        lbDescripcionArea.setText("Descripción:");

        areaAltaInputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaAltaInputNombreActionPerformed(evt);
            }
        });

        areaAltaInputDescipcion.setColumns(20);
        areaAltaInputDescipcion.setRows(5);
        jScrollPane1.setViewportView(areaAltaInputDescipcion);

        jScrollPane2.setViewportView(listaAreas);

        btnAgregarArea.setText("Agregar área");
        btnAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPresupuestoArea)
                                    .addComponent(lbNombreArea)
                                    .addComponent(lbDescripcionArea))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(areaAltaInputNombre)
                                    .addComponent(areaAltaInputPresupuesto)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnAgregarArea)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaAltaInputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombreArea))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPresupuestoArea)
                            .addComponent(areaAltaInputPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDescripcionArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarArea))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAreaActionPerformed
        
        try{
            System.out.println("entra boton");
             String nombre = areaAltaInputNombre.getText();
             String descripcion = areaAltaInputDescipcion.getText();
             double presupuesto = Double.parseDouble(areaAltaInputPresupuesto.getText());
             
             
             Area area = new Area(nombre, descripcion, presupuesto);
             this.sistema.agregarArea(area);
             
             
             
             areaAltaInputNombre.setText("");
             areaAltaInputDescipcion.setText("");
             areaAltaInputPresupuesto.setText("");
             javax.swing.JOptionPane.showMessageDialog(this, "Área agregada exitosamente");  
             
        }catch (NumberFormatException e){
            
            javax.swing.JOptionPane.showMessageDialog(this, "El presupuesto debe ser un número válido", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarAreaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        this.actualizarAreas();

    }//GEN-LAST:event_formWindowOpened

    private void areaAltaInputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaAltaInputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaAltaInputNombreActionPerformed
    
    private void actualizarAreas(){
        System.out.println("entra actualizar areas");
        ArrayList<String> nombresAreas = new ArrayList<>();

        for(int i = 0; i < this.sistema.getAreasOrdenadasPorNombre().size(); i++){
          nombresAreas.add(this.sistema.getAreasOrdenadasPorNombre().get(i).getNombre());
          
        }
       
        listaAreas.setListData(nombresAreas.toArray(new String[0]));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaAltaInputDescipcion;
    private javax.swing.JTextField areaAltaInputNombre;
    private javax.swing.JTextField areaAltaInputPresupuesto;
    private javax.swing.JButton btnAgregarArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDescripcionArea;
    private javax.swing.JLabel lbNombreArea;
    private javax.swing.JLabel lbPresupuestoArea;
    private javax.swing.JList<String> listaAreas;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void update(Observable o, Object arg) {
        if (o == sistema) {
            actualizarAreas();   
        }
    }
}
