/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Dominio.Areas.Area;
import Dominio.Personas.Empleado;
import Dominio.Personas.Manager;
import FuncionalidadTexto.ArchivoGrabacion;
import Sistema.Sistema;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Observer;
import java.util.Observable;
import javax.swing.JTextArea;


/**
 *
 * @author javierfernandez
 */
public class VentanaAltaEmpleado extends javax.swing.JFrame implements Observer {
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAltaEmpleado.class.getName());

    /**
     * Creates new form VentanaAltaEmpleado
     */
    public VentanaAltaEmpleado(Sistema sistema) {
        this.sistema = sistema;
        this.sistema.addObserver((Observer) this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        inputCedula = new javax.swing.JTextField();
        inputCelular = new javax.swing.JTextField();
        inputSalarioMensual = new javax.swing.JTextField();
        btnIngresarEmpleado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaManagers = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaAreas = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEmpleadoCv = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cédula", "Celular", "Salario Mensual", "Manager", "Área"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        jLabel1.setText("Nombre");

        jLabel2.setText("Cédula");

        jLabel3.setText("Celular");

        jLabel4.setText("Salario Mensual");

        btnIngresarEmpleado.setText("Ingresar Empleado");
        btnIngresarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEmpleadoActionPerformed(evt);
            }
        });

        jLabel7.setText("Manager");

        tablaManagers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Cedula"
            }
        ));
        jScrollPane4.setViewportView(tablaManagers);

        jScrollPane5.setViewportView(listaAreas);

        jLabel5.setText("Área");

        txtEmpleadoCv.setColumns(20);
        txtEmpleadoCv.setRows(5);
        jScrollPane2.setViewportView(txtEmpleadoCv);

        jLabel6.setText("Escriba a continuación su CV:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnIngresarEmpleado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(jLabel1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(inputNombre)
                                    .addComponent(inputCelular)
                                    .addComponent(inputSalarioMensual))))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(inputCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputSalarioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(59, 59, 59)
                        .addComponent(btnIngresarEmpleado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(110, 110, 110))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        actualizarEmpleados();
        actualizarAreas();
        actualizarManagers();



        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnIngresarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEmpleadoActionPerformed
        
        try{
            
        String nombre = inputNombre.getText();
        int cedula = Integer.parseInt(inputCedula.getText());
        String celular = inputCelular.getText();
        int salarioMensual = Integer.parseInt(inputSalarioMensual.getText());
        
        
        int filaManagerSeleccionada = tablaManagers.getSelectedRow();
        
        Object valorCedula = tablaManagers.getValueAt(filaManagerSeleccionada, 1);
        int cedulaManager = Integer.parseInt(valorCedula.toString());
        
        Manager manager = sistema.getListaPersonas().getManagerPorCedula(cedulaManager);
        
                
                
        String areaNombre = listaAreas.getSelectedValue();
        Area area = this.sistema.getListaAreas().getAreaPorNombre(areaNombre);
        
        
        
        
        Empleado empleado = new Empleado(nombre,cedula,celular,salarioMensual,manager);
        
        if (!this.sistema.validarPresupuestoArea(empleado, area, 12)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El área no cuenta con presupuesto disponible para cubrir el salario.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;

        }

        
        
        this.sistema.agregarEmpleado(empleado, area);
       
        guardarCv(String.valueOf(cedula), txtEmpleadoCv);
        
        }catch (NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "La cédula debe escribirse sin putnos ni guion y la antiguedad en años enteros.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarEmpleadoActionPerformed
    
    public void guardarCv(String cedula, JTextArea texto){
        
        Path carpetaCvs = Paths.get("cvs");

        try{
            
        Files.createDirectories(carpetaCvs); 
        
        String nombreArchivo = "CV" + cedula;
        Path archivoCv = carpetaCvs.resolve(nombreArchivo);

        
        
        ArchivoGrabacion arch = new ArchivoGrabacion(archivoCv.toString(), false);
        
        String[] textoCvPorLinea = texto.getText().split("\\R");
        for (String linea : textoCvPorLinea) {
        arch.grabarLinea(linea);
        }

        arch.cerrar();
        
        }catch (IOException e) {
            System.out.println("Error al hacer el archivo.");
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo guardar el CV.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }   
        
        

    }
    
    
    public void actualizarEmpleados() {
    javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaEmpleados.getModel();
    modeloTabla.setRowCount(0); 
    
    for (int i = 0; i < this.sistema.getListaPersonas().getEmpleadosOrdenados().size(); i++) {
        
        Empleado empleado = this.sistema.getListaPersonas().getEmpleadosOrdenados().get(i);
        
        
        
        modeloTabla.addRow(new Object[]{
            empleado.getNombre(),
            empleado.getCedula(),
            empleado.getCelular(),
            empleado.getSalarioMensual(),
            empleado.getManager().getNombre(),
            this.sistema.getAreaDelEmpleado(empleado) != null ? this.sistema.getAreaDelEmpleado(empleado).getNombre() : "Sin área",
            });
        
        }

    }
    
    private void actualizarAreas(){
        System.out.println("entra actualizar areas");
        ArrayList<String> nombresAreas = new ArrayList<>();

        for(int i = 0; i < this.sistema.getAreasOrdenadasPorNombre().size(); i++){
          nombresAreas.add(this.sistema.getAreasOrdenadasPorNombre().get(i).getNombre());
          
        }
       
        listaAreas.setListData(nombresAreas.toArray(new String[0]));
    }
    
    public void actualizarManagers() {
    javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaManagers.getModel();
    modeloTabla.setRowCount(0); 
    
    for (int i = 0; i < this.sistema.getManagersOrdenados().size(); i++) {
        
        Manager manager = this.sistema.getManagersOrdenados().get(i);
        
        modeloTabla.addRow(new Object[]{
            manager.getNombre(),
            manager.getCedula(),
            });
        }
    }
    
    @Override
    public void update(Observable o, Object arg) {
        if (o == sistema) {
            actualizarEmpleados();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarEmpleado;
    private javax.swing.JTextField inputCedula;
    private javax.swing.JTextField inputCelular;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputSalarioMensual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listaAreas;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaManagers;
    private javax.swing.JTextArea txtEmpleadoCv;
    // End of variables declaration//GEN-END:variables
}
