/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Dominio.Areas.Area;
import Sistema.Sistema;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;

/**
 *
 * @author javierfernandez
 */
public class VentanaAreaModificacion extends javax.swing.JFrame implements Observer {
    private Sistema sistema;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAreaModificacion.class.getName());

    /**
     * Creates new form VentanaAreaModificacion
     */
    public VentanaAreaModificacion(Sistema sistema) {
        this.sistema = sistema;
        this.sistema.addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAreas = new javax.swing.JList<>();
        lbNombreArea = new javax.swing.JLabel();
        lbPresupuestoArea = new javax.swing.JLabel();
        lbDescripcionArea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaInputDescripcion = new javax.swing.JTextArea();
        btnEditarArea = new javax.swing.JButton();
        areaInputNombre = new javax.swing.JTextField();
        areaInputPresupuesto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Área");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listaAreas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaAreasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaAreas);

        lbNombreArea.setText("Nombre:");

        lbPresupuestoArea.setText("Presupuesto (USD):");

        lbDescripcionArea.setText("Descripción:");

        areaInputDescripcion.setColumns(20);
        areaInputDescripcion.setRows(5);
        jScrollPane2.setViewportView(areaInputDescripcion);

        btnEditarArea.setText("Editar Área");
        btnEditarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAreaActionPerformed(evt);
            }
        });

        areaInputNombre.setEnabled(false);

        areaInputPresupuesto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcionArea)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarArea)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPresupuestoArea)
                            .addComponent(lbNombreArea))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(areaInputNombre)
                            .addComponent(areaInputPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombreArea)
                            .addComponent(areaInputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPresupuestoArea)
                            .addComponent(areaInputPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(lbDescripcionArea)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnEditarArea))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaAreasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaAreasValueChanged
        try{
            
        String areaSeleccionada = listaAreas.getSelectedValue();
        
        Area areaParaEditar = this.sistema.getAreaPorNOmbre(areaSeleccionada);
        
        areaInputNombre.setText(areaParaEditar.getNombre());
        areaInputPresupuesto.setText(String.valueOf(areaParaEditar.getPresupuesto()));
        areaInputDescripcion.setText(areaParaEditar.getDescripcion());
        
        }catch (NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Se debe selecionar un area", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_listaAreasValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    this.actualizarAreas();

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnEditarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAreaActionPerformed

        String areaSeleccionada = listaAreas.getSelectedValue();
        
        Area areaParaEditar = this.sistema.getAreaPorNOmbre(areaSeleccionada);

        String descripcion = areaInputDescripcion.getText();
        
        areaParaEditar.setDescripcion(descripcion);



        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarAreaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    private void actualizarAreas(){
        ArrayList<String> nombresAreas = new ArrayList<>();

        for(int i = 0; i < this.sistema.getAreasOrdenadasPorNombre().size(); i++){
          nombresAreas.add(this.sistema.getAreasOrdenadasPorNombre().get(i).getNombre());
          
        }
       
        listaAreas.setListData(nombresAreas.toArray(new String[0]));
    }

    
    //PREGUNTAR EN CLASE!!!
    @Override
    public void update(Observable o, Object arg) {
        if (o == sistema) {
            // Actualiza la interfaz gráfica en el hilo de eventos de Swing
            SwingUtilities.invokeLater(() -> {
                actualizarAreas();  // Método que actualiza el JList
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInputDescripcion;
    private javax.swing.JTextField areaInputNombre;
    private javax.swing.JTextField areaInputPresupuesto;
    private javax.swing.JButton btnEditarArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDescripcionArea;
    private javax.swing.JLabel lbNombreArea;
    private javax.swing.JLabel lbPresupuestoArea;
    private javax.swing.JList<String> listaAreas;
    // End of variables declaration//GEN-END:variables
}
