/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Dominio.Personas.Manager;
import Sistema.Sistema;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;

/**
 *
 * @author javierfernandez
 */
public class VentanaBajaManager extends javax.swing.JFrame implements Observer {
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBajaManager.class.getName());

    /**
     * Creates new form VentanaBajaManager
     */
    public VentanaBajaManager(Sistema sistema) {
        
        this.sistema = sistema;
        this.sistema.addObserver((Observer) this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEliminarManager = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaManager = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnEliminarManager.setText("Eliminar Manager");
        btnEliminarManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarManagerActionPerformed(evt);
            }
        });

        tablaManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cédula", "Años de antigüedad", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaManager);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(btnEliminarManager)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnEliminarManager)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        this.actualizarManagersSinEmpleados();


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarManagerActionPerformed

        
        try{
        int filaSeleccionada = tablaManager.getSelectedRow();
        
        String nombre = (String) tablaManager.getValueAt(filaSeleccionada, 0);
        int cedula = (Integer) tablaManager.getValueAt(filaSeleccionada, 1);
        String celular = (String) tablaManager.getValueAt(filaSeleccionada, 3);
        int antiguedad = (Integer) tablaManager.getValueAt(filaSeleccionada, 2);
        
        
        Manager manager = new Manager(nombre,cedula,celular,antiguedad);
        
        this.sistema.eliminarManager(manager);
        
        }catch (NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Se debe seleccionar una fila.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarManagerActionPerformed

    public void actualizarManagersSinEmpleados() {
    javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaManager.getModel();
    modeloTabla.setRowCount(0); 
    
    for (int i = 0; i < this.sistema.getManagersSinEmpleadosACargo().size(); i++) {
        Manager manager = this.sistema.getManagersSinEmpleadosACargo().get(i);
        
        modeloTabla.addRow(new Object[]{
            manager.getNombre(),
            manager.getCedula(),
            manager.getAnosDeAntiguedad(),
            manager.getCelular()
            });
        }
    }
    //PREGUNTAR EN CLASE!!!
    @Override
    public void update(Observable o, Object arg) {
        if (o == sistema) {
            // Actualiza la interfaz gráfica en el hilo de eventos de Swing
            SwingUtilities.invokeLater(() -> {
                actualizarManagersSinEmpleados();  // Método que actualiza el JList
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaManager;
    // End of variables declaration//GEN-END:variables
}
